coverage:
  status:
    project:
      default:
        target: 90%
      binary-traits:
        flags:
          - binary-traits
      bitarray:
        flags:
          - bitarray
      fa-compression:
        flags:
          - fa-compression
      memory-hints:
        flags:
          - memory-hints
      protein-metadata:
        flags:
          - protein-metadata
      sa-builder:
        flags:
          - sa-builder
      sa-index:
        target: 80%
        flags:
          - sa-index
      sa-server:
        flags:
          - sa-server
      text-compression:
        flags:
          - text-compression
    patch: off

flags:
  binary-traits:
    paths:
      - binary-traits
    carryforward: true
  bitarray:
    paths:
      - bitarray
    carryforward: true
  fa-compression:
    paths:
      - fa-compression
    carryforward: true
  memory-hints:
    paths:
      - memory-hints
    carryforward: true
  protein-metadata:
    paths:
      - protein-metadata
    carryforward: true
  sa-builder:
    paths:
      - sa-builder
    carryforward: true
  sa-index:
    paths:
      - sa-index
    carryforward: true
  sa-server:
    paths:
      - sa-server
    carryforward: true
  text-compression:
    paths:
      - text-compression
    carryforward: true

ignore:
  - "**/main.rs" # Ignore main.rs files
