//! The `fa-compression` crate provides multiple algorithms for compressing and decompressing
//! functional annotations. The algorithms are designed to work with the output generated by the
//! Unipept index builder.
//!
//! [`algorithm1`] encodes each annotation string on its own, with no shared state;
//! [`algorithm2`] compresses harder but needs a [`CompressionTable`](algorithm2::CompressionTable)
//! built over the whole database. See the module docs for which one fits.
#![warn(missing_docs)]

pub mod algorithm1;
pub mod algorithm2;
