[package]
name = "sa-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mmap = ["sa-index/mmap", "sa-mappings/mmap"]
preloaded-text = ["sa-index/preloaded-text", "sa-mappings/preloaded-text"]
preloaded-proteins = ["sa-index/preloaded-proteins", "sa-mappings/preloaded-proteins"]
preloaded-mapping = ["sa-index/preloaded-mapping"]

[dependencies]
axum = { version = "0.7.4", features = ["macros"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }
sa-index = { path = "../sa-index" }
clap = { version = "4.5.1", features = ["derive"] }
sa-mappings = { path = "../sa-mappings" }
